<?php

namespace AppBundle\Repository;

/**
 * Article_manufactorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article_manufactorRepository extends \Doctrine\ORM\EntityRepository
{
}
