<?php

namespace AppBundle\Repository;

/**
 * Article_tvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article_tvaRepository extends \Doctrine\ORM\EntityRepository
{
}
