<?php

namespace AppBundle\Repository;

/**
 * CaddieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaddieRepository extends \Doctrine\ORM\EntityRepository
{
}
