<?php

namespace AppBundle\Repository;

/**
 * User_paymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_paymentRepository extends \Doctrine\ORM\EntityRepository
{
}
