<?php

namespace AdminBundle\Repository;

/**
 * ManufactorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufactorRepository extends \Doctrine\ORM\EntityRepository
{
}
